CREATE DATABASE IF NOT EXISTS `siththam_directory`;
USE `siththam_directory`;

DROP TABLE IF EXISTS `PAINTINGS`;
DROP TABLE IF EXISTS `ARTISTS`;
DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `ARTISTS` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(100) NOT NULL,
    `Email` VARCHAR(100) NOT NULL UNIQUE,
    `Password` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`Id`)
    );

CREATE TABLE `PAINTINGS` (
    `Art_Id` INT NOT NULL AUTO_INCREMENT,
    `ArtName` VARCHAR(100) NOT NULL,
    `Artist_Id` INT,
    `ArtImage` LONGBLOB,
    `Price` DECIMAL(10,2),
    `Status` ENUM('AVAILABLE','SOLD','RESERVED') DEFAULT 'AVAILABLE',
    PRIMARY KEY (`Art_Id`),
    FOREIGN KEY (`Artist_Id`) REFERENCES ARTISTS(`Id`) ON DELETE CASCADE
    );

 CREATE TABLE `USERS` (
    `UserId` INT AUTO_INCREMENT,
    `UserName` VARCHAR(100) NOT NULL,
    `Email` VARCHAR(100) UNIQUE NOT NULL,
    `Password` VARCHAR(100),
    PRIMARY KEY (`UserId`)
    );


